$(document).ready(function(){
    $(window).scroll(function(){
        if($(document).scrollTop()>20){
            $('.navbar').addClass('custom-nav');
        }
        else{
            $('.navbar').removeClass('custom-nav');
        }
    });
});
$('.navbar-toggler').click(functiv)